on:
  push:
    branches:
      - master
      - main
  pull_request: {}

name: Test

jobs:
  build_and_test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: calcit-lang/setup-calcit@6a2e53ae41e4f0d5856a424b9ed4470d90ea6876

      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: nightly
          components: clippy

      - run: cargo build --release

      - run: mkdir dylibs/ && ls target/release/ && cp -v target/release/*.* dylibs/

      - run: calcit calcit.cirru
